// <auto-generated />
using System;
using Gameplay.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gameplay.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GameplayDbContext))]
    [Migration("20260713072038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gameplay")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gameplay.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BigBlind")
                        .HasColumnType("integer")
                        .HasColumnName("big_blind");

                    b.Property<Guid>("HostParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_participant_id");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("join_code");

                    b.Property<int>("SmallBlind")
                        .HasColumnType("integer")
                        .HasColumnName("small_blind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.ToTable("games", "gameplay");
                });

            modelBuilder.Entity("Gameplay.Domain.Entities.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_hands");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_hands_game_id");

                    b.ToTable("hands", "gameplay");
                });

            modelBuilder.Entity("Gameplay.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Chips")
                        .HasColumnType("integer")
                        .HasColumnName("chips");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("SittingOut")
                        .HasColumnType("boolean")
                        .HasColumnName("sitting_out");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("GameId")
                        .HasDatabaseName("ix_participants_game_id");

                    b.ToTable("participants", "gameplay");
                });

            modelBuilder.Entity("Gameplay.Domain.Entities.Hand", b =>
                {
                    b.HasOne("Gameplay.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hands_games_game_id");

                    b.OwnsMany("Gameplay.Domain.ValueObjects.HandAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<int>("SequenceNumber")
                                .HasColumnType("integer")
                                .HasColumnName("sequence_number");

                            b1.Property<int?>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("street");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.HasKey("HandId", "SequenceNumber")
                                .HasName("pk_hand_actions");

                            b1.HasIndex("ParticipantId")
                                .HasDatabaseName("ix_hand_actions_participant_id");

                            b1.ToTable("hand_actions", "gameplay");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_actions_hands_hand_id");

                            b1.HasOne("Gameplay.Domain.Entities.Participant", null)
                                .WithMany()
                                .HasForeignKey("ParticipantId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_hand_actions_participants_participant_id");
                        });

                    b.OwnsMany("Gameplay.Domain.ValueObjects.HandSeat", "Seats", b1 =>
                        {
                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<int>("StartingStack")
                                .HasColumnType("integer")
                                .HasColumnName("starting_stack");

                            b1.HasKey("HandId", "ParticipantId")
                                .HasName("pk_hand_seats");

                            b1.HasIndex("ParticipantId")
                                .HasDatabaseName("ix_hand_seats_participant_id");

                            b1.ToTable("hand_seats", "gameplay");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_seats_hands_hand_id");

                            b1.HasOne("Gameplay.Domain.Entities.Participant", null)
                                .WithMany()
                                .HasForeignKey("ParticipantId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_hand_seats_participants_participant_id");
                        });

                    b.Navigation("Actions");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Gameplay.Domain.Entities.Participant", b =>
                {
                    b.HasOne("Gameplay.Domain.Entities.Game", null)
                        .WithMany("Participants")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_games_game_id");
                });

            modelBuilder.Entity("Gameplay.Domain.Entities.Game", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
