<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1515;CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Web.Frontend\Web.Frontend.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Bunit" />
    <Using Include="Bunit.TestDoubles" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
