// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Statistics.Infrastructure.Data;

#nullable disable

namespace Statistics.Infrastructure.Data.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    partial class StatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("statistics")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Statistics.Domain.Entities.Hand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AbortedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aborted_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_hand");

                    b.ToTable("hand", "statistics");
                });

            modelBuilder.Entity("Statistics.Domain.Entities.Rebuy", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.HasKey("EventId")
                        .HasName("pk_rebuy");

                    b.ToTable("rebuy", "statistics");
                });

            modelBuilder.Entity("Statistics.Domain.Entities.Hand", b =>
                {
                    b.OwnsMany("Statistics.Domain.Entities.HandAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid")
                                .HasColumnName("event_id");

                            b1.Property<int>("SequenceNumber")
                                .HasColumnType("integer")
                                .HasColumnName("sequence_number");

                            b1.Property<int?>("AmountTo")
                                .HasColumnType("integer")
                                .HasColumnName("amount_to");

                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("type");

                            b1.Property<DateTimeOffset?>("UndoneAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("undone_at");

                            b1.HasKey("EventId", "SequenceNumber")
                                .HasName("pk_hand_action");

                            b1.HasIndex("HandId")
                                .HasDatabaseName("ix_hand_action_hand_id");

                            b1.ToTable("hand_action", "statistics");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_action_hand_hand_id");
                        });

                    b.OwnsMany("Statistics.Domain.ValueObjects.HandPot", "Pots", b1 =>
                        {
                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<int>("PotIndex")
                                .HasColumnType("integer")
                                .HasColumnName("pot_index");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.HasKey("HandId", "PotIndex")
                                .HasName("pk_hand_pot");

                            b1.ToTable("hand_pot", "statistics");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_pot_hand_hand_id");

                            b1.OwnsMany("Statistics.Domain.ValueObjects.HandPotWinner", "Winners", b2 =>
                                {
                                    b2.Property<Guid>("HandId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("hand_id");

                                    b2.Property<int>("PotIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("pot_index");

                                    b2.Property<Guid>("ParticipantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("participant_id");

                                    b2.HasKey("HandId", "PotIndex", "ParticipantId")
                                        .HasName("pk_hand_pot_winner");

                                    b2.ToTable("hand_pot_winner", "statistics");

                                    b2.WithOwner()
                                        .HasForeignKey("HandId", "PotIndex")
                                        .HasConstraintName("fk_hand_pot_winner_hand_pot_hand_id_pot_index");
                                });

                            b1.Navigation("Winners");
                        });

                    b.OwnsMany("Statistics.Domain.ValueObjects.HandResult", "Results", b1 =>
                        {
                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<int>("EndingChips")
                                .HasColumnType("integer")
                                .HasColumnName("ending_chips");

                            b1.Property<int>("Net")
                                .HasColumnType("integer")
                                .HasColumnName("net");

                            b1.Property<string>("ParticipantName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("participant_name");

                            b1.HasKey("HandId", "ParticipantId")
                                .HasName("pk_hand_result");

                            b1.ToTable("hand_result", "statistics");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_result_hand_hand_id");
                        });

                    b.OwnsMany("Statistics.Domain.ValueObjects.HandSeat", "Seats", b1 =>
                        {
                            b1.Property<Guid>("HandId")
                                .HasColumnType("uuid")
                                .HasColumnName("hand_id");

                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid")
                                .HasColumnName("participant_id");

                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("position");

                            b1.Property<int>("StartingChips")
                                .HasColumnType("integer")
                                .HasColumnName("starting_chips");

                            b1.HasKey("HandId", "ParticipantId")
                                .HasName("pk_hand_seat");

                            b1.ToTable("hand_seat", "statistics");

                            b1.WithOwner()
                                .HasForeignKey("HandId")
                                .HasConstraintName("fk_hand_seat_hand_hand_id");
                        });

                    b.Navigation("Actions");

                    b.Navigation("Pots");

                    b.Navigation("Results");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
